version: '2'
services:
    timesheet-app:
        image: timesheet
        external_links:
            - timesheet-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/Timesheet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timesheet-postgresql:
        extends:
            file: postgresql.yml
            service: timesheet-postgresql
